services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ./node_modules/.bin/ng serve --host 0.0.0.0 --poll 1
    volumes:
      - ./frontend:/app
    expose:
      - "49153:49153"
    ports:
      - "4200:4200"
      - "49153:49153"
    