services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - FIRESTORE_EMULATOR_HOST=firestore:8598
      - GCLOUD_PROJECT=test
      - GCP_LOCATION_ID=us-east1
      - FIREBASE_PROJECT_ID=test

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ./node_modules/.bin/ng serve --host 0.0.0.0 --poll 1
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"

  firestore:
    build:
      context: ./test/firestore
      dockerfile: Dockerfile
    expose:
      - "8080"
      - "4000"
    ports:
      - "8080:8080"
      - "4000:4000"
    volumes:
      - ./test/firestore/firebase.json:/app/firebase.json
    working_dir: /app
    command: bash -c "firebase init | firebase emulators:start --project=test"
    